// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanatEvi.Data.Concrete.EfCore.Repositories;

#nullable disable

namespace SanatEvi.Data.Migrations
{
    [DbContext(typeof(SanatEviContext))]
    partial class SanatEviContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(131),
                            Description = "Resim kursları, sanatseverlere resim becerilerini geliştirme ve yaratıcılıklarını keşfetme fırsatı sunan bir eğitim programıdır. Bu kurslar, çeşitli resim teknikleri ve malzemeleri üzerinde odaklanırken, katılımcılara renk, kompozisyon ve perspektif gibi temel sanat prensiplerini öğretir. Öğrenciler, uzman ressamlardan rehberlik alırken, kendi sanatsal tarzlarını keşfeder ve eserlerini yaratıcı bir şekilde ifade ederler. Resim kursları, sanatı sevdiren, ilham veren ve katılımcılara güven veren bir ortamda sanatsal becerilerini geliştirmek isteyen herkes için idealdir.",
                            ImageUrl = "resim-jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(146),
                            Name = "Resim",
                            Url = "resim"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(151),
                            Description = "Seramik ve çömlekçilik, binlerce yıllık bir geçmişe sahip olan zanaat ve sanat dalıdır. Bu disiplin, kilin şekillendirilmesi, pişirilmesi ve süslemesiyle özgün ve dayanıklı seramik eserlerin yaratılmasını içerir. Seramik ve çömlekçilik kursları, katılımcılara temel teknikleri öğretirken, el becerilerini ve yaratıcılıklarını geliştirme imkanı sunar. Öğrenciler, çömlek tekerleği kullanarak vazolar, tabaklar ve heykeller gibi çeşitli eserler yapabilir, glazelerle renklendirme ve dekorasyon tekniklerini öğrenebilirler. Bu kurslar, sanatsal ifadeye ilgi duyan ve kendi benzersiz seramik eserlerini yaratmak isteyen herkese hitap eder.",
                            ImageUrl = "seramik-comlekcilik.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(153),
                            Name = "Seramik Ve Çömlekçilik",
                            Url = "seramik-comlekcilik"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(156),
                            Description = "Mozaik kursları, katılımcılara renkli ve çarpıcı mozaik eserlerinin nasıl oluşturulacağını öğretmek için mükemmel bir fırsattır. Bu kurslar, mozaik sanatının temel prensiplerini ve tekniklerini kapsar. Öğrenciler, farklı renk ve şekillerdeki mozaik parçalarını kullanarak, çeşitli yüzeylere güzel desenler ve görüntüler oluşturabilir. Kurslar genellikle farklı mozaik malzemelerinin kullanımını, kesmeyi, yerleştirmeyi ve tutkalı içerir. Mozaik kursları, yaratıcılığı teşvik ederken, kişilerin el becerilerini geliştirmelerini ve kendilerini sanatla ifade etmelerini sağlar.",
                            ImageUrl = "mozaik.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(156),
                            Name = "Mozaik",
                            Url = "mozaik"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(159),
                            Description = "Cam işleme kursu, camın farklı tekniklerle şekillendirilmesi ve dekoratif eserlerin yapılmasını öğreten bir eğitim programıdır. Bu kurslar, cam kesme, cam eritme, cam füzyonu, cam süsleme ve cam oyma gibi çeşitli tekniklere odaklanabilir. Katılımcılar, camdan vazolar, heykeller, takılar, lambalar ve vitray panolar gibi çeşitli objeler oluşturabilir. Cam işleme kursları, camın ışığı yansıtma özelliği ve renk çeşitliliğiyle sanatsal ifade imkanı sağlar. Bu kurslar, el becerilerini geliştirmek isteyen, estetik açıdan etkileyici cam eserler yaratmak isteyen herkese hitap eder.",
                            ImageUrl = "cam-isleme.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(160),
                            Name = "Cam İşleme",
                            Url = "cam-isleme"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(162),
                            Description = "Cam işleme kursu, camın farklı tekniklerle şekillendirilmesi ve dekoratif eserlerin yapılmasını öğreten bir eğitim programıdır. Bu kurslar, cam kesme, cam eritme, cam füzyonu, cam süsleme ve cam oyma gibi çeşitli tekniklere odaklanabilir. Katılımcılar, camdan vazolar, heykeller, takılar, lambalar ve vitray panolar gibi çeşitli objeler oluşturabilir. Cam işleme kursları, camın ışığı yansıtma özelliği ve renk çeşitliliğiyle sanatsal ifade imkanı sağlar. Bu kurslar, el becerilerini geliştirmek isteyen, estetik açıdan etkileyici cam eserler yaratmak isteyen herkese hitap eder.",
                            ImageUrl = "ahsap-isleme-sanati.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(163),
                            Name = "Ahşap İşleme",
                            Url = "ahsap-isleme-sanati"
                        });
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classtime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPerson")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Classtime = "120 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7296),
                            CurrentPerson = 25,
                            Description = "Bu tür kurslar, resim yapmaya yeni başlayanlar için temel resim becerilerini öğretmeyi amaçlar. Renk teorisi, kompozisyon, perspektif, ışık-gölge gibi temel resim prensipleri ve teknikleri bu kurslar kapsamında öğretilebilir.",
                            EndDate = new DateTime(2023, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "temel-resim-kurslari.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7307),
                            Price = 1000m,
                            StartingDate = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Temel Resim Kursu",
                            Url = "temel-resim-kurslari"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Classtime = "80 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7317),
                            CurrentPerson = 25,
                            Description = "Yağlı boya resim tekniğine odaklanan kurslardır. Yağlı boya malzemeleri, fırça teknikleri, renk karışımları ve tablo üzerinde çalışma gibi konular bu kurslar kapsamında ele alınır.",
                            EndDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "yagli-boya-kursu.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7318),
                            Price = 1200m,
                            StartingDate = new DateTime(2023, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Yağlı Boya Kursu",
                            Url = "yagli-boya-kursu"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Classtime = "70 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7323),
                            CurrentPerson = 25,
                            Description = "Karakalem tekniğiyle resim yapmayı öğretmeyi amaçlayan kurslardır. Karakalem fırçaları, tonlama, çizim teknikleri ve gölgelendirme gibi konular bu kurslar içinde yer alır.",
                            EndDate = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "karakalem-kursu.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7324),
                            Price = 800m,
                            StartingDate = new DateTime(2023, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Karakalem Kursu",
                            Url = "karakalem-kursu.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Classtime = "100 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7329),
                            CurrentPerson = 25,
                            Description = "Portre resim yapmayı öğretmeyi hedefleyen kurslardır. İnsan yüzünün anatomisi, yüz ifadeleri, ışık-gölge ilişkileri ve detaylandırma gibi konular bu kurslar kapsamında ele alınır.",
                            EndDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "portre-resim-kursu.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7330),
                            Price = 1000m,
                            StartingDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Portre Resim Kursu",
                            Url = "portre-resim-kursu"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Classtime = "60 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7334),
                            CurrentPerson = 25,
                            Description = "Akrilik boya kullanarak resim yapmayı öğretmeyi hedefleyen kurslardır. Akrilik boya malzemeleri, fırça teknikleri, renk geçişleri ve katmanlar gibi konular bu kurslar kapsamında ele alınır.",
                            EndDate = new DateTime(2023, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "akrilik-resim-kursu.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7335),
                            Price = 1400m,
                            StartingDate = new DateTime(2023, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Akrilik Boya Kursu",
                            Url = "akrilik-resim-kursu"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Classtime = "100 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7339),
                            CurrentPerson = 20,
                            Description = "Bu kurs, seramik malzemeleri, el şekillendirme teknikleri, kilin hazırlanması, merkezleme ve şekil verme gibi temel becerileri öğretir. Katılımcılar, çeşitli seramik formları oluşturma ve kilin pişirme sürecini deneyimleme fırsatı bulurlar.",
                            EndDate = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "temel-seramik-kursu.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7340),
                            Price = 1500m,
                            StartingDate = new DateTime(2023, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Temel Seramik Kursu",
                            Url = "temel-seramik-kursu"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Classtime = "50 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7345),
                            CurrentPerson = 20,
                            Description = "Bu kurs, çömlekçilik tekerleği üzerinde çalışmayı öğretir. Katılımcılar, çömlekçilik tekerleği kullanarak çeşitli kaplar, vazolar veya tabaklar gibi formlar oluşturma becerilerini geliştirir. Ayrıca, eserlerin sonraki aşamaları olan kurutma, glazelenme ve pişirme süreçlerini de öğrenirler.",
                            EndDate = new DateTime(2023, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "carkta-comlekcilik-kursu.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7346),
                            Price = 1400m,
                            StartingDate = new DateTime(2023, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Çarkta Çömlekçilik Kursu",
                            Url = "carkta-comlekcilik-kursu"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Classtime = "100 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7350),
                            CurrentPerson = 20,
                            Description = "Bu kurs, seramik parçaların dekoratif tekniklerle süslenmesini öğretir. Katılımcılar, boyama, sırlama, transfer baskı, kabartma ve serigrafi gibi farklı dekoratif yöntemleri kullanarak seramik eserlerini kişiselleştirme becerisini kazanırlar.",
                            EndDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "dekoratif-seramik-kurs.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7351),
                            Price = 1000m,
                            StartingDate = new DateTime(2023, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dekoratif Seramik Kursu",
                            Url = "dekoratif-seramik-kurs"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Classtime = "120 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7355),
                            CurrentPerson = 20,
                            Description = "Bu kurs, mozaik sanatının temellerini öğretir. Mozaik malzemeleri seçme, kesme, düzenleme ve yapıştırma teknikleri gibi konuları kapsar. Katılımcılar, küçük projelerde pratik yaparak mozaik sanatına giriş yaparlar.",
                            EndDate = new DateTime(2023, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "temel-mozaik-kursu.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7356),
                            Price = 1100m,
                            StartingDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Temel Mozaik Kursu",
                            Url = "temel-mozaik-kursu"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Classtime = "85 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7364),
                            CurrentPerson = 20,
                            Description = "Bu kurs, mozaik tablolar oluşturmayı öğretir. Katılımcılar, ahşap bir tablo yüzeyine mozaik parçalarını yerleştirerek kişisel ve dekoratif bir tablo yapma becerilerini geliştirirler. Mozaik tasarımı, renk uyumu ve yapıştırma teknikleri kursun odak noktalarıdır.",
                            EndDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "mozaik-tablo-kursu.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7365),
                            Price = 1350m,
                            StartingDate = new DateTime(2023, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mozaik Tablo Kursu",
                            Url = "mozaik-tablo-kursu"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Classtime = "150 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7370),
                            CurrentPerson = 20,
                            Description = "Bu kurs, vitray cam tekniklerini öğretir. Katılımcılar, cam levhaları kesme, lehimleme ve farklı renklerdeki camları bir araya getirerek vitray pencereler, lambalar veya dekoratif cam paneller gibi ürünler yapmayı öğrenirler.",
                            EndDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "vitray-cam-kursu.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7371),
                            Price = 2000m,
                            StartingDate = new DateTime(2023, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Vitray Cam Kursu",
                            Url = "vitray-cam-kursu"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Classtime = "100 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7377),
                            CurrentPerson = 25,
                            Description = "Bu kurs, cam yüzeyine kabartma efektleri verme tekniklerini öğretir. Katılımcılar, cam levhaları ısıtma ve şekillendirme yöntemleriyle üç boyutlu desenler ve kabartmalar oluştururlar.",
                            EndDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "cam-kabartma-kursu.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7378),
                            Price = 1000m,
                            StartingDate = new DateTime(2023, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cam Kabartma Kursu",
                            Url = "cam-kabartma-kursu"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Classtime = "130 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7382),
                            CurrentPerson = 25,
                            Description = "Bu kurs, ahşap işleme tekniklerinin temellerini öğretir. Katılımcılar, ahşap malzemeleri kesme, şekillendirme, zımparalama ve birleştirme gibi temel becerileri kazanarak küçük projeler yaparlar.",
                            EndDate = new DateTime(2023, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "temel-ahsap-isleme-kursu.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7383),
                            Price = 1500m,
                            StartingDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Temel Ahşap İşleme Kursu",
                            Url = "temel-ahsap-isleme-kursu"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Classtime = "100 saat",
                            CreatedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7387),
                            CurrentPerson = 20,
                            Description = "Bu kurs, ahşap oyma sanatını öğretir. Katılımcılar, çeşitli oyma teknikleri kullanarak ahşap üzerine desenler ve kabartmalar oluştururlar. Ahşap oyma aletlerini kullanma becerilerini geliştirirler ve kendi oyma projelerini tamamlarlar.",
                            EndDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "ahsap-oyma-kurs.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 7, 20, 21, 42, 47, 676, DateTimeKind.Local).AddTicks(7388),
                            Price = 1100m,
                            StartingDate = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ahşap Oyma Kursu",
                            Url = "ahsap-oyma-kursu"
                        });
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.CourseInstructor", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstructorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseInstructors");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.CourseUser", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseUser");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            UserId = "1",
                            DateRegistration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 1,
                            UserId = "2",
                            DateRegistration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 2,
                            UserId = "1",
                            DateRegistration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CourseId = 3,
                            UserId = "2",
                            DateRegistration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("DateOfBirth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EducationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Address = "Halide Edip Adıvar Mahallesi Darülaceze Caddesi No:3A BOMONTİ / ŞİŞLİ",
                            City = "İstanbul",
                            ConcurrencyStamp = "6398f2bc-517b-45e1-9ccd-d85d13097682",
                            DateOfBirth = 2000,
                            EducationStatus = "Lisans",
                            EmailConfirmed = false,
                            FirstName = "Mehmet",
                            Gender = "Erkek",
                            ImageUrl = "mehmet-derik.jpg",
                            LastName = "Derik",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cbe89ab7-9481-471f-9c60-ff2efca975c4",
                            TwoFactorEnabled = false,
                            Url = "mehmet-derik"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            Address = "Meliha Avni Sezen Cad. Sakız Ağacı Sok. No: 47/C Esentepe",
                            City = "İstanbul",
                            ConcurrencyStamp = "42c089f5-1f3d-4c8c-acbb-e9a2b0090cd8",
                            DateOfBirth = 1998,
                            EducationStatus = "Lisans",
                            EmailConfirmed = false,
                            FirstName = "Selen",
                            Gender = "Kadın",
                            ImageUrl = "selen-sargin.jpg",
                            LastName = "Sargın",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "09e5f2b2-a43d-4d90-9425-2f3aa0ff9291",
                            TwoFactorEnabled = false,
                            Url = "selen-sargın"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SanatEvi.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Course", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.CourseInstructor", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.Course", "Course")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SanatEvi.Entity.Concrete.Instructor", "Instructor")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.CourseUser", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SanatEvi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Instructor", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Course", b =>
                {
                    b.Navigation("CourseInstructors");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Instructor", b =>
                {
                    b.Navigation("CourseInstructors");
                });
#pragma warning restore 612, 618
        }
    }
}
