// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanatEvi.Data.Concrete.EfCore.Contexts;

#nullable disable

namespace SanatEvi.Data.Migrations
{
    [DbContext(typeof(SanatEviContext))]
    partial class SanatEviContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "0dc901ea-d93e-4a13-904b-66b58f29d7ec",
                            RoleId = "b222516e-df0e-497a-99ae-39fad2778d7f"
                        },
                        new
                        {
                            UserId = "fcec27df-3573-4d1b-b43e-bb3e515196db",
                            RoleId = "f6f4901a-aa43-482e-8487-a384faac4165"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 447, DateTimeKind.Local).AddTicks(6194),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 447, DateTimeKind.Local).AddTicks(6204),
                            UserId = "0dc901ea-d93e-4a13-904b-66b58f29d7ec"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 447, DateTimeKind.Local).AddTicks(6210),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 447, DateTimeKind.Local).AddTicks(6210),
                            UserId = "fcec27df-3573-4d1b-b43e-bb3e515196db"
                        });
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("CourseId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1659),
                            Description = "Resim kursları, sanatseverlere resim becerilerini geliştirme ve yaratıcılıklarını keşfetme fırsatı sunan bir eğitim programıdır. Bu kurslar, çeşitli resim teknikleri ve malzemeleri üzerinde odaklanırken, katılımcılara renk, kompozisyon ve perspektif gibi temel sanat prensiplerini öğretir. Öğrenciler, uzman ressamlardan rehberlik alırken, kendi sanatsal tarzlarını keşfeder ve eserlerini yaratıcı bir şekilde ifade ederler. Resim kursları, sanatı sevdiren, ilham veren ve katılımcılara güven veren bir ortamda sanatsal becerilerini geliştirmek isteyen herkes için idealdir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1668),
                            Name = "Resim",
                            Url = "resim"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1671),
                            Description = "Seramik ve çömlekçilik, binlerce yıllık bir geçmişe sahip olan zanaat ve sanat dalıdır. Bu disiplin, kilin şekillendirilmesi, pişirilmesi ve süslemesiyle özgün ve dayanıklı seramik eserlerin yaratılmasını içerir. Seramik ve çömlekçilik kursları, katılımcılara temel teknikleri öğretirken, el becerilerini ve yaratıcılıklarını geliştirme imkanı sunar. Öğrenciler, çömlek tekerleği kullanarak vazolar, tabaklar ve heykeller gibi çeşitli eserler yapabilir, glazelerle renklendirme ve dekorasyon tekniklerini öğrenebilirler. Bu kurslar, sanatsal ifadeye ilgi duyan ve kendi benzersiz seramik eserlerini yaratmak isteyen herkese hitap eder.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1671),
                            Name = "Seramik Ve Çömlekçilik",
                            Url = "seramik-comlekcilik"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1673),
                            Description = "Mozaik kursları, katılımcılara renkli ve çarpıcı mozaik eserlerinin nasıl oluşturulacağını öğretmek için mükemmel bir fırsattır. Bu kurslar, mozaik sanatının temel prensiplerini ve tekniklerini kapsar. Öğrenciler, farklı renk ve şekillerdeki mozaik parçalarını kullanarak, çeşitli yüzeylere güzel desenler ve görüntüler oluşturabilir. Kurslar genellikle farklı mozaik malzemelerinin kullanımını, kesmeyi, yerleştirmeyi ve tutkalı içerir. Mozaik kursları, yaratıcılığı teşvik ederken, kişilerin el becerilerini geliştirmelerini ve kendilerini sanatla ifade etmelerini sağlar.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1673),
                            Name = "Mozaik",
                            Url = "mozaik"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1674),
                            Description = "Cam işleme kursu, camın farklı tekniklerle şekillendirilmesi ve dekoratif eserlerin yapılmasını öğreten bir eğitim programıdır. Bu kurslar, cam kesme, cam eritme, cam füzyonu, cam süsleme ve cam oyma gibi çeşitli tekniklere odaklanabilir. Katılımcılar, camdan vazolar, heykeller, takılar, lambalar ve vitray panolar gibi çeşitli objeler oluşturabilir. Cam işleme kursları, camın ışığı yansıtma özelliği ve renk çeşitliliğiyle sanatsal ifade imkanı sağlar. Bu kurslar, el becerilerini geliştirmek isteyen, estetik açıdan etkileyici cam eserler yaratmak isteyen herkese hitap eder.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1675),
                            Name = "Cam İşleme",
                            Url = "cam-isleme"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1676),
                            Description = "Cam işleme kursu, camın farklı tekniklerle şekillendirilmesi ve dekoratif eserlerin yapılmasını öğreten bir eğitim programıdır. Bu kurslar, cam kesme, cam eritme, cam füzyonu, cam süsleme ve cam oyma gibi çeşitli tekniklere odaklanabilir. Katılımcılar, camdan vazolar, heykeller, takılar, lambalar ve vitray panolar gibi çeşitli objeler oluşturabilir. Cam işleme kursları, camın ışığı yansıtma özelliği ve renk çeşitliliğiyle sanatsal ifade imkanı sağlar. Bu kurslar, el becerilerini geliştirmek isteyen, estetik açıdan etkileyici cam eserler yaratmak isteyen herkese hitap eder.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1676),
                            Name = "Ahşap İşleme",
                            Url = "ahsap-isleme-sanati"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1677),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1677),
                            Name = "Güzel Sanatlar",
                            Url = "güzel-sanatlar"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1678),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1679),
                            Name = "El Sanatları",
                            Url = "el-sanatlari"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1680),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 448, DateTimeKind.Local).AddTicks(1680),
                            Name = "Hovi ve Sanat",
                            Url = "hobi-ve-sanat"
                        });
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPerson")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(28),
                            CurrentPerson = 25,
                            Description = "Bu tür kurslar, resim yapmaya yeni başlayanlar için temel resim becerilerini öğretmeyi amaçlar. Renk teorisi, kompozisyon, perspektif, ışık-gölge gibi temel resim prensipleri ve teknikleri bu kurslar kapsamında öğretilebilir.",
                            Duration = "120 saat",
                            ImageUrl = "temel-resim-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(35),
                            Name = "Temel Resim Kursu",
                            Price = 1000m,
                            TeacherId = 1,
                            Url = "temel-resim-kursu"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(43),
                            CurrentPerson = 25,
                            Description = "Yağlı boya resim tekniğine odaklanan kurslardır. Yağlı boya malzemeleri, fırça teknikleri, renk karışımları ve tablo üzerinde çalışma gibi konular bu kurslar kapsamında ele alınır.",
                            Duration = "80 saat",
                            ImageUrl = "yagli-boya-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(43),
                            Name = "Yağlı Boya Kursu",
                            Price = 1200m,
                            TeacherId = 1,
                            Url = "yagli-boya-kursu"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(46),
                            CurrentPerson = 25,
                            Description = "Karakalem tekniğiyle resim yapmayı öğretmeyi amaçlayan kurslardır. Karakalem fırçaları, tonlama, çizim teknikleri ve gölgelendirme gibi konular bu kurslar içinde yer alır.",
                            Duration = "70 saat",
                            ImageUrl = "kara-kalem-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(47),
                            Name = "Karakalem Kursu",
                            Price = 800m,
                            TeacherId = 1,
                            Url = "kara-kalem-kursu"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(49),
                            CurrentPerson = 25,
                            Description = "Portre resim yapmayı öğretmeyi hedefleyen kurslardır. İnsan yüzünün anatomisi, yüz ifadeleri, ışık-gölge ilişkileri ve detaylandırma gibi konular bu kurslar kapsamında ele alınır.",
                            Duration = "100 saat",
                            ImageUrl = "portre-resim-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(49),
                            Name = "Portre Resim Kursu",
                            Price = 1000m,
                            TeacherId = 1,
                            Url = "portre-resim-kursu"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(51),
                            CurrentPerson = 25,
                            Description = "Akrilik boya kullanarak resim yapmayı öğretmeyi hedefleyen kurslardır. Akrilik boya malzemeleri, fırça teknikleri, renk geçişleri ve katmanlar gibi konular bu kurslar kapsamında ele alınır.",
                            Duration = "60 saat",
                            ImageUrl = "akrilik-resim-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(57),
                            Name = "Akrilik Boya Kursu",
                            Price = 1400m,
                            TeacherId = 1,
                            Url = "akrilik-resim-kursu"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(67),
                            CurrentPerson = 20,
                            Description = "Bu kurs, seramik malzemeleri, el şekillendirme teknikleri, kilin hazırlanması, merkezleme ve şekil verme gibi temel becerileri öğretir. Katılımcılar, çeşitli seramik formları oluşturma ve kilin pişirme sürecini deneyimleme fırsatı bulurlar.",
                            Duration = "100 saat",
                            ImageUrl = "temel-seramik-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(68),
                            Name = "Temel Seramik Kursu",
                            Price = 1500m,
                            TeacherId = 3,
                            Url = "temel-seramik-kursu"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(70),
                            CurrentPerson = 20,
                            Description = "Bu kurs, çömlekçilik tekerleği üzerinde çalışmayı öğretir. Katılımcılar, çömlekçilik tekerleği kullanarak çeşitli kaplar, vazolar veya tabaklar gibi formlar oluşturma becerilerini geliştirir. Ayrıca, eserlerin sonraki aşamaları olan kurutma, glazelenme ve pişirme süreçlerini de öğrenirler.",
                            Duration = "50 saat",
                            ImageUrl = "carkta-comlekcilik-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(70),
                            Name = "Çarkta Çömlekçilik Kursu",
                            Price = 1400m,
                            TeacherId = 3,
                            Url = "carkta-comlekcilik-kursu"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(72),
                            CurrentPerson = 20,
                            Description = "Bu kurs, seramik parçaların dekoratif tekniklerle süslenmesini öğretir. Katılımcılar, boyama, sırlama, transfer baskı, kabartma ve serigrafi gibi farklı dekoratif yöntemleri kullanarak seramik eserlerini kişiselleştirme becerisini kazanırlar.",
                            Duration = "100 saat",
                            ImageUrl = "dekoratif-seramik-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(72),
                            Name = "Dekoratif Seramik Kursu",
                            Price = 1000m,
                            TeacherId = 3,
                            Url = "dekoratif-seramik-kursu"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(74),
                            CurrentPerson = 20,
                            Description = "Bu kurs, mozaik sanatının temellerini öğretir. Mozaik malzemeleri seçme, kesme, düzenleme ve yapıştırma teknikleri gibi konuları kapsar. Katılımcılar, küçük projelerde pratik yaparak mozaik sanatına giriş yaparlar.",
                            Duration = "120 saat",
                            ImageUrl = "temel-mozaik-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(74),
                            Name = "Temel Mozaik Kursu",
                            Price = 1100m,
                            TeacherId = 2,
                            Url = "temel-mozaik-kursu"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(76),
                            CurrentPerson = 20,
                            Description = "Bu kurs, mozaik tablolar oluşturmayı öğretir. Katılımcılar, ahşap bir tablo yüzeyine mozaik parçalarını yerleştirerek kişisel ve dekoratif bir tablo yapma becerilerini geliştirirler. Mozaik tasarımı, renk uyumu ve yapıştırma teknikleri kursun odak noktalarıdır.",
                            Duration = "85 saat",
                            ImageUrl = "mozaik-tablo-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(77),
                            Name = "Mozaik Tablo Kursu",
                            Price = 1350m,
                            TeacherId = 2,
                            Url = "mozaik-tablo-kursu"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(79),
                            CurrentPerson = 20,
                            Description = "Bu kurs, vitray cam tekniklerini öğretir. Katılımcılar, cam levhaları kesme, lehimleme ve farklı renklerdeki camları bir araya getirerek vitray pencereler, lambalar veya dekoratif cam paneller gibi ürünler yapmayı öğrenirler.",
                            Duration = "150 saat",
                            ImageUrl = "vitray-cam-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(79),
                            Name = "Vitray Cam Kursu",
                            Price = 2000m,
                            TeacherId = 2,
                            Url = "vitray-cam-kursu"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(81),
                            CurrentPerson = 25,
                            Description = "Bu kurs, cam yüzeyine kabartma efektleri verme tekniklerini öğretir. Katılımcılar, cam levhaları ısıtma ve şekillendirme yöntemleriyle üç boyutlu desenler ve kabartmalar oluştururlar.",
                            Duration = "100 saat",
                            ImageUrl = "cam-kabartma-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(81),
                            Name = "Cam Kabartma Kursu",
                            Price = 1000m,
                            TeacherId = 2,
                            Url = "cam-kabartma-kursu"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(83),
                            CurrentPerson = 25,
                            Description = "Bu kurs, ahşap işleme tekniklerinin temellerini öğretir. Katılımcılar, ahşap malzemeleri kesme, şekillendirme, zımparalama ve birleştirme gibi temel becerileri kazanarak küçük projeler yaparlar.",
                            Duration = "130 saat",
                            ImageUrl = "temel-ahsap-isleme-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(83),
                            Name = "Temel Ahşap İşleme Kursu",
                            Price = 1500m,
                            TeacherId = 4,
                            Url = "temel-ahsap-isleme-kursu"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(86),
                            CurrentPerson = 20,
                            Description = "Bu kurs, ahşap oyma sanatını öğretir. Katılımcılar, çeşitli oyma teknikleri kullanarak ahşap üzerine desenler ve kabartmalar oluştururlar. Ahşap oyma aletlerini kullanma becerilerini geliştirirler ve kendi oyma projelerini tamamlarlar.",
                            Duration = "100 saat",
                            ImageUrl = "ahsap-oyma-kursu.jpeg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(86),
                            Name = "Ahşap Oyma Kursu",
                            Price = 1100m,
                            TeacherId = 4,
                            Url = "ahsap-oyma-kursu"
                        });
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.CourseCategory", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CourseCategories");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            CourseId = 1,
                            CategoryId = 6
                        },
                        new
                        {
                            CourseId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            CategoryId = 6
                        },
                        new
                        {
                            CourseId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            CourseId = 3,
                            CategoryId = 6
                        },
                        new
                        {
                            CourseId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            CourseId = 4,
                            CategoryId = 6
                        },
                        new
                        {
                            CourseId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            CourseId = 5,
                            CategoryId = 6
                        },
                        new
                        {
                            CourseId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            CourseId = 6,
                            CategoryId = 7
                        },
                        new
                        {
                            CourseId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            CourseId = 7,
                            CategoryId = 7
                        },
                        new
                        {
                            CourseId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            CourseId = 8,
                            CategoryId = 7
                        },
                        new
                        {
                            CourseId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            CourseId = 9,
                            CategoryId = 7
                        },
                        new
                        {
                            CourseId = 10,
                            CategoryId = 3
                        },
                        new
                        {
                            CourseId = 10,
                            CategoryId = 8
                        },
                        new
                        {
                            CourseId = 11,
                            CategoryId = 4
                        },
                        new
                        {
                            CourseId = 11,
                            CategoryId = 8
                        },
                        new
                        {
                            CourseId = 12,
                            CategoryId = 4
                        },
                        new
                        {
                            CourseId = 12,
                            CategoryId = 7
                        },
                        new
                        {
                            CourseId = 13,
                            CategoryId = 5
                        },
                        new
                        {
                            CourseId = 13,
                            CategoryId = 8
                        },
                        new
                        {
                            CourseId = 14,
                            CategoryId = 5
                        },
                        new
                        {
                            CourseId = 14,
                            CategoryId = 8
                        });
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b222516e-df0e-497a-99ae-39fad2778d7f",
                            Description = "Yöneticilerin rolü bu.",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "f6f4901a-aa43-482e-8487-a384faac4165",
                            Description = "Diğer tüm kullanıcıların rolü bu.",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DateOfBirth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EducationStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Yetenekli ve deneyimli bir resim sanatçısı ve eğitmenim. Sanatsal yeteneklerimi öğrencilere aktarmaktan keyif alıyorum ve onları motive ederek yaratıcılıklarını geliştirmelerine yardımcı oluyorum. Çeşitli sanatsal tekniklerle resim yapmayı öğretme konusunda uzmanım ve öğrencilerimin bireysel ihtiyaçlarına odaklanarak etkili dersler sunuyorum.",
                            Address = "Bahçelievler",
                            Branch = "Resim",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(2945),
                            DateOfBirth = 1994,
                            EducationStatus = "Lisans",
                            FirstName = "Ali",
                            Gender = "Erkek",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Asaf",
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(2951),
                            Phone = "02164785696",
                            PhotoUrl = "ali-asaf.jpg",
                            Url = "ali-asaf"
                        },
                        new
                        {
                            Id = 2,
                            About = "Tutkulu, motive edici ve öğrencilere ilham veren bir eğitmenim.Yaratıcı ve yenilikçi düşünce tarzıyla ders içeriğini zenginleştiriyorum.Sabırlı ve anlayışlı bir tutumla öğrencilerin özgüvenlerini artırıyorum.Takım çalışmasına yatkın ve iletişim becerileri güçlüyüm.",
                            Address = "Kadıköy",
                            Branch = "Mozaik",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(2957),
                            DateOfBirth = 1990,
                            EducationStatus = "Lisans",
                            FirstName = "Zeynep",
                            Gender = "Kadın",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hafsa",
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(2957),
                            Phone = "05567789839",
                            PhotoUrl = "zeynep-hafsa.jpg",
                            Url = "zeynep-hafsa"
                        },
                        new
                        {
                            Id = 3,
                            About = "Seramik sanatında uzmanlaşmış, yaratıcı ve öğrenci odaklı bir seramik öğretmeniyim. 10 yılı aşkın deneyimimle öğrencilere sanatsal yeteneklerini geliştirmede rehberlik ettim. Çeşitli seramik teknikleri, döküm, el işçiliği ve glazürleme konusunda bilgi ve becerilere sahibim. Öğrencilerin sanatsal ifade ve özgüvenlerini artırmak için etkili ders planları ve projeler tasarlarım.",
                            Address = "Şirinevler",
                            Branch = "Seramik",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(2961),
                            DateOfBirth = 1992,
                            EducationStatus = "Lisans",
                            FirstName = "Ahmet",
                            Gender = "Erkek",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Salih",
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(2961),
                            Phone = "05067782089",
                            PhotoUrl = "ahmet-salih.jpg",
                            Url = "ahmet-salih"
                        },
                        new
                        {
                            Id = 4,
                            About = "Tecrübeli ahşap ustası ve tutkulu öğretmen olarak, öğrencilere ahşap işleme sanatını öğretme ve onların yaratıcı becerilerini geliştirme konusunda uzmanım. Eğitim materyallerini ve öğretim yöntemlerini kişiselleştirerek öğrencilerin ilgi ve ihtiyaçlarına uygun dersler sunarım. Motive edici bir yaklaşım benimseyerek öğrencilerin başarıya ulaşmasına katkıda bulunurum.",
                            Address = "Eyüp",
                            Branch = "Ahşap",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(2963),
                            DateOfBirth = 1990,
                            EducationStatus = "Lisans",
                            FirstName = "Ela",
                            Gender = "Kadın",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Suna",
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(2964),
                            Phone = "05447658990",
                            PhotoUrl = "ela-suna.jpg",
                            Url = "ela-suna"
                        },
                        new
                        {
                            Id = 5,
                            About = "Henüz bir eğitmen atanmadı.",
                            Address = "Beşiktaş",
                            Branch = "Güzel Sanatlar",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(2966),
                            DateOfBirth = 1990,
                            EducationStatus = "Lisans",
                            FirstName = "Genel",
                            Gender = "Kadın",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Eğitmen",
                            ModifiedDate = new DateTime(2023, 8, 30, 4, 33, 19, 449, DateTimeKind.Local).AddTicks(2966),
                            Phone = "05467678904",
                            PhotoUrl = "default-profile.jpg",
                            Url = "genel-egitmen"
                        });
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0dc901ea-d93e-4a13-904b-66b58f29d7ec",
                            AccessFailedCount = 0,
                            Address = "Kemalpaşa Mh. Zühtübey Sk. No:12 D:3 Üsküdar",
                            City = "İstanbul",
                            ConcurrencyStamp = "c002fd5b-f3ca-477e-b3f8-2075e98a8fe7",
                            DateOfBirth = new DateTime(1983, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "muratyilmaz@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Murat",
                            Gender = "Erkek",
                            LastName = "yılmaz",
                            LockoutEnabled = true,
                            Name = " ",
                            NormalizedEmail = "MURATYILMAZ@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEFBITt39JmbXvpdmso/HiAE6nFfehnmBpNfqQC0c/wdXRSDiALdlKcIuTj62Fo3J7A==",
                            PhoneNumber = "+905436478990",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "fcec27df-3573-4d1b-b43e-bb3e515196db",
                            AccessFailedCount = 0,
                            Address = "Barbaros Bulvarı Feda İş Hanı K:5 D:23 Beşiktaş",
                            City = "İstanbul",
                            ConcurrencyStamp = "5298dbea-1b69-4f2f-8f6a-bc5fb90ccfd7",
                            DateOfBirth = new DateTime(1983, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cemrekendirli@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Cemre",
                            Gender = "Kadın",
                            LastName = "Kendirli",
                            LockoutEnabled = true,
                            Name = " ",
                            NormalizedEmail = "CEMREKENDIRLI@GMAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEOtm6/8zEPE23H4CYvFIOjcsAv8qnp0nCp+jTqBaXn1RRVAr7oxZdNrvFow+tcV/Ew==",
                            PhoneNumber = "+904556677888",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SanatEvi.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Cart", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.CartItem", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SanatEvi.Entity.Concrete.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Course", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.CourseCategory", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SanatEvi.Entity.Concrete.Course", "Course")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Order", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.OrderItem", b =>
                {
                    b.HasOne("SanatEvi.Entity.Concrete.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SanatEvi.Entity.Concrete.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Course", b =>
                {
                    b.Navigation("CourseCategories");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SanatEvi.Entity.Concrete.Teacher", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
